#ifndef SHADER_BASE_COMMON_H
#define SHADER_BASE_COMMON_H

#ifdef __cplusplus
#include <cstdint>
using uint = uint32_t;
#endif


// Push Constant

struct PushConstants {
	uint sample_batch;
};

struct ToneMappingPushConstants {
	float exposure;
};

// Descriptor set & Binding

#define RAY_TRACING_DYNAMIC_SET 0
#define RAY_TRACING_IMAGE_SET 1
#define RAY_TRACING_UNIFORM_SET 2
#define RAY_TRACING_SKYBOX_SET 3

#define COMPUTE_TONE_MAPPING_SET 0



#define BINDING_RAY_TRACING_SCENE_DYNAMIC_INFO 0

#define BINDING_RAY_TRACING_RENDERING_TARGET_IMAGE 0

#define BINDING_RAY_TRACING_SCENE_STATIC_INFO 0
#define BINDING_RAY_TRACING_TLAS 1
#define BINDING_RAY_TRACING_VERTICES 2
#define BINDING_RAY_TRACING_INDICES 3
#define BINDING_RAY_TRACING_MATERIAL 4
#define BINDING_RAY_TRACING_GEOMETRY 5
#define BINDING_RAY_TRACING_LIGHT 6
#define BINDING_RAY_TRACING_TEXCOORD0 7
#define BINDING_RAY_TRACING_TEXTURE_ARRAY 8
#define BINDING_RAY_TRACING_NORMAL 9
#define BINDING_RAY_TRACING_TANGENT 10

#define BINDING_RAY_TRACING_SKYBOX_TEXTURE_ARRAY 0

#define BINDING_COMPUTE_TONE_MAPPING_HDR_IMAGE 0
#define BINDING_COMPUTE_TONE_MAPPING_LDR_IMAGE 1

// Buffer Flag
#define BUFFER_FLAG_HAS_NORMALS 0x01
#define BUFFER_FLAG_HAS_TANGENTS 0x02
#define BUFFER_FLAG_HAS_TEXCOORDS 0x04

// Material Type
#define MATERIAL_TYPE_COOK_TORRANCE 0

// Light Type
#define LIGHT_TYPE_MESH 0 
#define LIGHT_TYPE_DIRECTIONAL 1
#define LIGHT_TYPE_POINT 2
#define LIGHT_TYPE_SPOT 3
#define LIGHT_TYPE_SKYBOX 4


// Alpha Mode
#define ALPHA_MODE_OPAQUE 0
#define ALPHA_MODE_MASK 1
#define ALPHA_MODE_BLEND 2

#endif // !SHADER_BASE_COMMON_H
